name: SimpleItemsLite
version: '${version}'
main: net.duart.simpleitemslite.SimpleItemsLite
api-version: '1.20'

commands:
  simpleitemslite:
    description: Main command for SimpleItemsLite
    usage: /simpleitemslite give (item)
    aliases:
      - sil

listeners:
  - net.duart.simpleitemslite.rainbowbridge.RainbowItemListener
  - net.duart.simpleitemslite.doublejump.JumpItemListener
  - net.duart.simpleitemslite.electriccharge.ElectricItemListener
  - net.duart.simpleitemslite.infinitewater.MagicWaterItemListener
  - net.duart.simpleitemslite.funbow.FunBowItemListener