name: SimpleItemsLite
version: '${version}'
main: net.duart.simpleitemslite.SimpleItemsLite
api-version: '1.20'

commands:
  simpleitemslite:
    description: Main command for SimpleItemsLite
    usage: /simpleitemslite give (item)
    aliases:
      - sil